package nl.robinlaugs.dealership.data.orm.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.NoArgsConstructor;
import nl.robinlaugs.dealership.domain.Car;

@DynamoDBTable(tableName = "")
@NoArgsConstructor
public class DynamoDBCar extends Car {

    public DynamoDBCar(Car car) {
        super(car.getId(), car.getBrand(), car.getType(), car.getYear());
    }

    @Override
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return super.getId();
    }

    @Override
    @DynamoDBRangeKey(attributeName = "brand")
    public String getBrand() {
        return super.getBrand();
    }

    @Override
    @DynamoDBAttribute(attributeName = "type")
    public String getType() {
        return super.getType();
    }

    @Override
    @DynamoDBAttribute(attributeName = "year")
    public int getYear() {
        return super.getYear();
    }

}
